FROM maven:3-eclipse-temurin-21 AS cache
COPY application /tmp/application
COPY frontend /tmp/frontend
COPY frameworks /tmp/frameworks
COPY modules /tmp/modules
COPY entities /tmp/entities
COPY providers /tmp/providers
COPY runtimes /tmp/runtimes
COPY triggers /tmp/triggers
COPY templates /tmp/templates
COPY pom.xml /tmp/pom.xml
WORKDIR /tmp
RUN mvn dependency:go-offline
RUN mvn clean generate-resources -pl frontend

FROM scratch
LABEL org.opencontainers.image.source=https://github.com/scc-digitalhub/digitalhub-core
WORKDIR /cache
COPY --from=cache /root/.m2 /cache/.m2
COPY --from=cache /tmp/frontend/target /cache/frontend/target
COPY --from=cache /tmp/frontend/console/node_modules /cache/frontend/console/node_modules