# Spring configuration
spring:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    database-platform: ${JDBC_DIALECT:org.hibernate.dialect.H2Dialect}
  datasource:
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    password: ${JDBC_PASS:password}
    username: ${JDBC_USER:sa}
    url: ${JDBC_URL:jdbc:h2:file:./data/db}
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                password: guest
                host: 192.168.49.1
                port: '5672'
                username: guest
      bindings:
        entityEvent-rabbit-in-0:
          destination: entity-topic
          group: dh_core
        entityEvent-rabbit-out-0:
          destination: entity-topic
          group: dh_core
      rabbit:
        bindings:
          entityEvent-rabbit-in-0:
            consumer:
              declare-exchange: false
              bind-queue: false
              queue-name-group-only: true
          entityEvent-rabbit-out-0:
            producer:
              declare-exchange: false
              bind-queue: false
              queue-name-group-only: true
    function:
      definition: logEntityEvent
  data:
    web:
      pageable:
        one-indexed-parameters: 'true'
        max-page-size: '100'
        default-page-size: '10'
  h2:
    console:
      enabled: ${H2_CONSOLE:true}

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'

# Runtimes
runtime:
  nefertem:
    image: ${RUNTIME_NEFERTEM_IMAGE:ghcr.io/scc-digitalhub/digitalhub-core-wrapper-nefertem:latest}
  dbt:
    image: ${RUNTIME_DBT_IMAGE:ghcr.io/scc-digitalhub/digitalhub-core-wrapper-dbt:latest}

# Mlrun config
mlrun:
  api:
    function-url: http://192.168.49.2:30070/api/v1/func/{project}/{function}?versioned=true
    submit-job: http://192.168.49.2:30060/mlrun/api/v1/submit_job
    project-url: http://192.168.49.2:30070/api/v1/projects/{project}
    log-url: http://192.168.49.2:30060/mlrun/api/v1/log/{project}/{uid}
    run-url: http://192.168.49.2:30070/api/v1/run/{project}/{uid}

# Spring Docs
springdoc:
  api-docs:
    path: /v1/api-docs

# Kaniko config
kaniko:
  target:
    path: kubernetes/target
  source:
    path: kubernetes/source

# Kubernetes
kubernetes:
  namespace: ${K8S_NAMESPACE:default}
  config:
    config-map: ${DH_CONFIG_COMMON_MAPS:digitalhub-common-env}
    secret: ${DH_CONFIG_COMMON_SECRETS:digitalhub-common-creds}

# Application endpoint
application:
  endpoint: ${DH_ENDPOINT:http://localhost:8080}
