# Spring configuration
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: ${JDBC_DIALECT:org.hibernate.dialect.H2Dialect}
  datasource:
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    password: ${JDBC_PASS:password}
    username: ${JDBC_USER:sa}
    url: ${JDBC_URL:jdbc:h2:file:./data/db}

  data:
    web:
      pageable:
        one-indexed-parameters: 'true'
        max-page-size: '100'
        default-page-size: '10'
  h2:
    console:
      enabled: ${H2_CONSOLE:true}

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'

# Runtimes
runtime:
  nefertem:
    image: ${RUNTIME_NEFERTEM_IMAGE:ghcr.io/scc-digitalhub/digitalhub-core-wrapper-nefertem:latest}
  dbt:
    image: ${RUNTIME_DBT_IMAGE:ghcr.io/scc-digitalhub/digitalhub-core-wrapper-dbt:latest}


# Spring Docs
springdoc:
  api-docs:
    path: /v1/api-docs

# Kaniko config
kaniko:
  target:
    path: kubernetes/target
  source:
    path: kubernetes/source

# Kubernetes
kubernetes:
  namespace: ${K8S_NAMESPACE:default}
  config:
    config-map: ${DH_CONFIG_COMMON_MAPS:digitalhub-common-env}
    secret: ${DH_CONFIG_COMMON_SECRETS:digitalhub-common-creds}

# Application endpoint
application:
  endpoint: ${DH_ENDPOINT:http://localhost:8080}


# Conditional Configuration Cloud
cloud-stream:
  enabled: true
  services:
    rabbit:
      enabled: true


# OLD SPRING CLOUD CONFIG
#
#  cloud:
#    stream:
#      bindings:
#        entity-out-0:
#          destination: entityTopic
#          group: dhCoreQueue
#          content-type: application/json
#          binder: rabbit
#      rabbit:
#        bindings:
#          entity-out-0:
#            producer:
#              bind-queue: true
#              declare-exchange: true
#              exchange-durable: true
#              routing-key: 'entityRoutingKey'
#              exchangeType: topic     # Set the exchange type (e.g., topic, direct, fanout)