---
apiVersion: v1
kind: Service
metadata:
  name: core
  labels:
    app.kubernetes.io/name: core
    app.kubernetes.io/instance: core
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30180
  selector:
    app.kubernetes.io/name: core
    app.kubernetes.io/instance: dhcore
